getHTMLCoursesSuccess:
  has_layout: false
getHTMLCourseSummary:
  has_layout: false
subscriptionsSuccess:
  has_layout: true
  layout:     layout_subscriptions
subscriptionsCourses:
  has_layout: false  